services:
  app:
    image: ghcr.io/tobiaswaelde/ezprint:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: file:/data/app.db
      NUXT_SESSION_TTL_HOURS: 168
      DATA_DIR: /data
    ports:
      - '3000:3000'
    volumes:
      - app-data:/data

volumes:
  app-data:
